repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn", #only display messages
            "-sn", #Don't display score
            "--rcfile=.pylintrc", # Link to your config file
            "--load-plugins=pylint.extensions.docparams", # load an extension
          ]
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c './venv/Scripts/pip3 freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]
